SELECT POSITION, COLUMN_NAME,
COLUMN_NAME || ' ' || DATA_TYPE_NAME || '(' || LENGTH || CASE WHEN SCALE IS NOT NULL THEN CONCAT(',', SCALE) ELSE '' END || ')' AS "COLUMN LIST SQL",
'`' || COLUMN_NAME || '` ' || CASE WHEN CS_DATA_TYPE_NAME = 'STRING' THEN 'string' ELSE LOWER(DATA_TYPE_NAME) END || ',' AS "COLUMN LIST ATHENA"
FROM TABLE_COLUMNS
WHERE SCHEMA_NAME = 'SCHEMA'
AND TABLE_NAME = 'TABLE'
ORDER BY POSITION;
